### ISSUE TITLE
Algorithm-specific arguments in constructor

### ISSUE THREAD

**Issue by WardBrian** [WardBrian/scikit-stan#4]
It would be nice to expose things like chains, number of iterations, etc, as a dictionary argument or by using **kwargs

**Comment by alizma** [comment]
This has been completed as of commit ``3588a4a``. Parameters are passed as a dictionary with fields corresponding to each field the same way that the CmdStanPy algorithm parameters are called. Validation also occurs through the CmdStanPy parameter validation helper methods. 

Because the optimization and variational inference choices have several options for algorithms to use, admissible names for that field of the constructor have been changed to ``sample``, ``optimize``, and ``variational`` with defaults for each following CmdStanPy.
